AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3EncryptionKey:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: S3 Encryption Key
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
  SecureComplianceDataBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: secure-compliance-data
      ObjectLockEnabled: true
      VersioningConfiguration:
        Status: Enabled
