AWSTemplateFormatVersion: '2010-09-09'
Resources:
  SourceBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: my-company-data
      VersioningConfiguration:
        Status: Enabled
      ReplicationConfiguration:
        Role: !GetAtt ReplicationRole.Arn
        Rules:
          - Id: ReplicationRule
            Status: Enabled
            Destination:
              Bucket: !Sub 'arn:aws:s3:::dr-backup-bucket'
  DestinationBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: dr-backup-bucket
      VersioningConfiguration:
        Status: Enabled
  ReplicationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sts:AssumeRole
